# workflow
name: Deploy Infrastructure

# event trigger
on:
 push:
  branches: 
      - "group-one"

permissions:
        id-token: write
        contents: read

jobs:

  provision-ec2:
        runs-on: ubuntu-latest

        steps:
         - name: Checkout git repository
           uses: actions/checkout@v4

         
          #  uses: aws-actions/configure-aws-credentials@v4.0.2
          #  with:
            # audience: sts.amazonaws.com
            # aws-region: eu-west-2
            # role-to-assume: arn:aws:iam::637423323865:role/git-action

         - name: "Configure AWS Credentials"
           uses: aws-actions/configure-aws-credentials@v4.0.2
           with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: eu-west-2

         - name: HashiCorp - Setup Terraform
           uses: hashicorp/setup-terraform@v3.1.1

         - name: Change directory
           run: |
            cd terraform
            terraform init
            terraform validate
            terraform apply -auto-approve

       #  - name: Terraform Init
       #   run: terraform init

       #  - name: Terraform Validate
       #    run: terraform validate

        #  - name: Terraform Plan
        #    run: terraform plan
        #    env:
        #     AWS_REGION: eu-west-2
        # - name: Terraform Apply
        #   run: terraform apply -auto-approve
